addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.14")

addSbtPlugin("com.47deg" % "sbt-microsites" % "1.3.4")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.5.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.3")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.12")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.2.0")
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "1.0.1")
